"""initial schema

Revision ID: 4b8612116768
Revises: 
Create Date: 2026-08-23 22:05:40.358906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8612116768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ordering does not make a significant difference for SQLite since it does not check for a table that's referenced when creating it.
    # For other databases, this leniency may not exist. Since 'aisle' and 'edges' have foreign keys, the tables where those FKs are from should be created first. In this case 'stores' -> 'aisles' -> 'edges'
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aisles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aisle_a_id', sa.INTEGER(), nullable=False),
    sa.Column('aisle_b_id', sa.INTEGER(), nullable=False),
    sa.Column('distance', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['aisle_a_id'], ['aisles.id'], ),
    sa.ForeignKeyConstraint(['aisle_b_id'], ['aisles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ordering comment is the same as in the above function, but mirrored here since the tables are being dropped.
    op.drop_table('edges')
    op.drop_table('aisles')
    op.drop_table('stores')
    # ### end Alembic commands ###